SELECT * FROM `comment`;

ALTER TABLE `comment` ADD `createAt` TIMESTAMP;
ALTER TABLE `comment` ADD `updateAt` TIMESTAMP;

ALTER TABLE `comment` MODIFY createAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE `comment` MODIFY updateAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;